apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: redpanda
  name: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redpanda
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redpanda
    spec:
      containers:
        - name: redpanda
          image: vectorized/redpanda:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
              name: http
              protocol: TCP