apiVersion: v1
kind: Service
metadata:
  name: redpanda
  labels:
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/name: redpanda
spec:
  type: ClusterIP
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: rpc
      port: 33145
      targetPort: 33145
  selector:
    app.kubernetes.io/name: redpanda