apiVersion: v1
kind: Service
metadata:
  name: redpanda
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  ports:
    - name: http
      port: 9092
      targetPort: 9092
  selector:
    app.kubernetes.io/name: redpanda
  type: ClusterIP