apiVersion: v1
kind: Service
metadata:
  name: redpanda-service
  labels:
    app: redpanda
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    - name: kafka-tcp
      port: 9092
      targetPort: kafka-tcp
      protocol: TCP
  selector:
    app: redpanda