apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: todo-trigger
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.kafka.event
      source: /apis/v1/namespaces/default/kafkasources/kafka-source-todo#todo-created
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: todo
    uri: /todo/create