apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source-todo
spec:
  bootstrapServers:
    - redpanda:9092
  topics:
    - todo-created
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default